// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: v1/discover.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_v1_discover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_discover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_v1_discover_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Programs      []*Program             `protobuf:"bytes,2,rep,name=programs,proto3" json:"programs,omitempty"`
	Episodes      []*Episode             `protobuf:"bytes,3,rep,name=episodes,proto3" json:"episodes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,7,opt,name=total_pages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_v1_discover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_discover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_v1_discover_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *SearchResponse) GetPrograms() []*Program {
	if x != nil {
		return x.Programs
	}
	return nil
}

func (x *SearchResponse) GetEpisodes() []*Episode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

func (x *SearchResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type FeaturedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturedRequest) Reset() {
	*x = FeaturedRequest{}
	mi := &file_v1_discover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturedRequest) ProtoMessage() {}

func (x *FeaturedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_discover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturedRequest.ProtoReflect.Descriptor instead.
func (*FeaturedRequest) Descriptor() ([]byte, []int) {
	return file_v1_discover_proto_rawDescGZIP(), []int{2}
}

type FeaturedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Programs      []*Program             `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturedResponse) Reset() {
	*x = FeaturedResponse{}
	mi := &file_v1_discover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturedResponse) ProtoMessage() {}

func (x *FeaturedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_discover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturedResponse.ProtoReflect.Descriptor instead.
func (*FeaturedResponse) Descriptor() ([]byte, []int) {
	return file_v1_discover_proto_rawDescGZIP(), []int{3}
}

func (x *FeaturedResponse) GetPrograms() []*Program {
	if x != nil {
		return x.Programs
	}
	return nil
}

var File_v1_discover_proto protoreflect.FileDescriptor

const file_v1_discover_proto_rawDesc = "" +
	"\n" +
	"\x11v1/discover.proto\x12\vthmanyah.v1\x1a\x1cgoogle/api/annotations.proto\x1a\fv1/cms.proto\x1a\x1copenapi/v3/annotations.proto\"W\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1c\n" +
	"\tpage_size\x18\x03 \x01(\x05R\tpage_size\"\xa1\x02\n" +
	"\x0eSearchResponse\x125\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x15.thmanyah.v1.CategoryR\n" +
	"categories\x120\n" +
	"\bprograms\x18\x02 \x03(\v2\x14.thmanyah.v1.ProgramR\bprograms\x120\n" +
	"\bepisodes\x18\x03 \x03(\v2\x14.thmanyah.v1.EpisodeR\bepisodes\x12 \n" +
	"\vtotal_count\x18\x04 \x01(\x05R\vtotal_count\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1c\n" +
	"\tpage_size\x18\x06 \x01(\x05R\tpage_size\x12 \n" +
	"\vtotal_pages\x18\a \x01(\x05R\vtotal_pages\"\x11\n" +
	"\x0fFeaturedRequest\"D\n" +
	"\x10FeaturedResponse\x120\n" +
	"\bprograms\x18\x01 \x03(\v2\x14.thmanyah.v1.ProgramR\bprograms2\xa0\x02\n" +
	"\x0fDiscoverService\x12\xa5\x01\n" +
	"\bFeatured\x12\x1c.thmanyah.v1.FeaturedRequest\x1a\x1d.thmanyah.v1.FeaturedResponse\"\\\xbaG8\x1a6Returns a list of featured programs that are published\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/discover/featured\x12e\n" +
	"\x06Search\x12\x1a.thmanyah.v1.SearchRequest\x1a\x1b.thmanyah.v1.SearchResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/discover/searchB\x14Z\x12thmanyah/api/v1;v1b\x06proto3"

var (
	file_v1_discover_proto_rawDescOnce sync.Once
	file_v1_discover_proto_rawDescData []byte
)

func file_v1_discover_proto_rawDescGZIP() []byte {
	file_v1_discover_proto_rawDescOnce.Do(func() {
		file_v1_discover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_discover_proto_rawDesc), len(file_v1_discover_proto_rawDesc)))
	})
	return file_v1_discover_proto_rawDescData
}

var file_v1_discover_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_discover_proto_goTypes = []any{
	(*SearchRequest)(nil),    // 0: thmanyah.v1.SearchRequest
	(*SearchResponse)(nil),   // 1: thmanyah.v1.SearchResponse
	(*FeaturedRequest)(nil),  // 2: thmanyah.v1.FeaturedRequest
	(*FeaturedResponse)(nil), // 3: thmanyah.v1.FeaturedResponse
	(*Category)(nil),         // 4: thmanyah.v1.Category
	(*Program)(nil),          // 5: thmanyah.v1.Program
	(*Episode)(nil),          // 6: thmanyah.v1.Episode
}
var file_v1_discover_proto_depIdxs = []int32{
	4, // 0: thmanyah.v1.SearchResponse.categories:type_name -> thmanyah.v1.Category
	5, // 1: thmanyah.v1.SearchResponse.programs:type_name -> thmanyah.v1.Program
	6, // 2: thmanyah.v1.SearchResponse.episodes:type_name -> thmanyah.v1.Episode
	5, // 3: thmanyah.v1.FeaturedResponse.programs:type_name -> thmanyah.v1.Program
	2, // 4: thmanyah.v1.DiscoverService.Featured:input_type -> thmanyah.v1.FeaturedRequest
	0, // 5: thmanyah.v1.DiscoverService.Search:input_type -> thmanyah.v1.SearchRequest
	3, // 6: thmanyah.v1.DiscoverService.Featured:output_type -> thmanyah.v1.FeaturedResponse
	1, // 7: thmanyah.v1.DiscoverService.Search:output_type -> thmanyah.v1.SearchResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_discover_proto_init() }
func file_v1_discover_proto_init() {
	if File_v1_discover_proto != nil {
		return
	}
	file_v1_cms_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_discover_proto_rawDesc), len(file_v1_discover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_discover_proto_goTypes,
		DependencyIndexes: file_v1_discover_proto_depIdxs,
		MessageInfos:      file_v1_discover_proto_msgTypes,
	}.Build()
	File_v1_discover_proto = out.File
	file_v1_discover_proto_goTypes = nil
	file_v1_discover_proto_depIdxs = nil
}
