// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: v1/options.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Auth requirements for RPCs
type AuthOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Required      bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`      // Whether auth is required
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`             // Required roles (if any)
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"` // Required permissions (if any)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOptions) Reset() {
	*x = AuthOptions{}
	mi := &file_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOptions) ProtoMessage() {}

func (x *AuthOptions) ProtoReflect() protoreflect.Message {
	mi := &file_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOptions.ProtoReflect.Descriptor instead.
func (*AuthOptions) Descriptor() ([]byte, []int) {
	return file_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *AuthOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AuthOptions) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AuthOptions) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var file_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthOptions)(nil),
		Field:         50001,
		Name:          "thmanyah.v1.auth",
		Tag:           "bytes,50001,opt,name=auth",
		Filename:      "v1/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional thmanyah.v1.AuthOptions auth = 50001;
	E_Auth = &file_v1_options_proto_extTypes[0]
)

var File_v1_options_proto protoreflect.FileDescriptor

const file_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x10v1/options.proto\x12\vthmanyah.v1\x1a google/protobuf/descriptor.proto\"a\n" +
	"\vAuthOptions\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions:N\n" +
	"\x04auth\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2\x18.thmanyah.v1.AuthOptionsR\x04authB\x14Z\x12thmanyah/api/v1;v1b\x06proto3"

var (
	file_v1_options_proto_rawDescOnce sync.Once
	file_v1_options_proto_rawDescData []byte
)

func file_v1_options_proto_rawDescGZIP() []byte {
	file_v1_options_proto_rawDescOnce.Do(func() {
		file_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_options_proto_rawDesc), len(file_v1_options_proto_rawDesc)))
	})
	return file_v1_options_proto_rawDescData
}

var file_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_options_proto_goTypes = []any{
	(*AuthOptions)(nil),                // 0: thmanyah.v1.AuthOptions
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_v1_options_proto_depIdxs = []int32{
	1, // 0: thmanyah.v1.auth:extendee -> google.protobuf.MethodOptions
	0, // 1: thmanyah.v1.auth:type_name -> thmanyah.v1.AuthOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_options_proto_init() }
func file_v1_options_proto_init() {
	if File_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_options_proto_rawDesc), len(file_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_v1_options_proto_goTypes,
		DependencyIndexes: file_v1_options_proto_depIdxs,
		MessageInfos:      file_v1_options_proto_msgTypes,
		ExtensionInfos:    file_v1_options_proto_extTypes,
	}.Build()
	File_v1_options_proto = out.File
	file_v1_options_proto_goTypes = nil
	file_v1_options_proto_depIdxs = nil
}
